authors:
  jeffotter:
    name: Jeff Ott        # Author name
    description: Darc Team Research Analytics Scientist # Author description
    avatar: https://github.com/jeffotter.png         # Author avatar
    url: https://github.com/Jeffotter            # Author website URL
  mason:
    name: Mason Jiang        # Author name
    description: 🪨 Senior Data Engineer @DARC GSB Team # Author description
    avatar: https://github.com/mpj2104.png         # Author avatar
    url: https://github.com/mpj2104            # Author website URL
  nrapstin:
    name: Natalya Rapstine                                       # Author name
    description: 🦄 Research Computing Specialist @DARC GSB Team  # Author description
    avatar: https://github.com/natalya-patrikeeva.png            # Author avatar
    url: https://github.com/natalya-patrikeeva                   # Author website URL
  awn:
    name: Amy Ng                                       # Author name
    description: Lead Research Analytics Scientist @DARC GSB Team  # Author description
    avatar: https://github.com/alwaysawn.png            # Author avatar
    url: https://github.com/alwaysawn                   # Author website URL